/**
 * Test-only stand-in for `virtual:pwa-register/react`.
 *
 * That module is generated by vite-plugin-pwa at build/dev time. Vitest runs with
 * its own config (vitest.config.ts) which does not load the plugin, so without this
 * stub any test that mounts <App /> would fail to resolve the import. The alias is
 * wired up in vitest.config.ts.
 */
export function useRegisterSW(_options?: unknown) {
  return {
    needRefresh: [false, () => {}] as [boolean, (value: boolean) => void],
    offlineReady: [false, () => {}] as [boolean, (value: boolean) => void],
    updateServiceWorker: async (_reloadPage?: boolean) => {},
  };
}
